# Generated by Django 5.2.1 on 2025-06-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_project_short_link_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_link_key',
            field=models.CharField(default='Tfuule', max_length=32),
        ),
    ]
